my_dbt_proj:
  outputs:
    dev:
      account: re14111.eu-west-1
      database: transformed_dev
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: transform
      schema: snowflake_dbt
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
