WITH source AS (
    SELECT *
    FROM {{ source('system_s', 'CdmCarePlan') }}
    WHERE {{ filter_by_clinic() }}
)

SELECT
    id                                  AS id,
    cdmreviewid                         AS cdm_review_id,
    patientcarername                    AS patient_carer_name,
    disclosecareplanconsent             AS disclose_care_plan_consent,
    medicationlist                      AS medication_list,
    printmedicationlist                 AS print_medication_list,
    medicationconcerns                  AS medication_concerns,
    medicationconcerndetails            AS medication_concern_details,
    medicationissuesdiscussed           AS medication_issues_discussed,
    healthwellnessconcerns              AS health_wellness_concerns,
    healthwellnessimprovements          AS health_wellness_improvements,
    healthwellnessother                 AS health_wellness_other,
    manageconditiondiet                 AS manage_condition_diet,
    manageconditiondietdetails          AS manage_condition_diet_details,
    manageconditionweight               AS manage_condition_weight,
    manageconditionweightdetails        AS manage_condition_weight_details,
    manageconditionbreathing            AS manage_condition_breathing,
    manageconditionbreathingdetails     AS manage_condition_breathing_details,
    manageconditionappt                 AS manage_condition_appt,
    manageconditionapptdetails          AS manage_condition_appt_details,
    manageconditionother                AS manage_condition_other,
    previousgoalsoverall                AS previous_goals_overall,
    previousgoalsoverallprogress        AS previous_goals_overall_progress,
    previousgoalslifestyle              AS previous_goals_lifestyle,
    previousgoalslifestyleprogress      AS previous_goals_lifestyle_progress,
    futuregoalsoverall                  AS future_goals_overall,
    futuregoalsoverallplan              AS future_goals_overall_plan,
    futuregoalslifestyle                AS future_goals_lifestyle,
    futuregoalslifestyleplan            AS future_goals_lifestyle_plan,
    referredtophn                       AS referred_to_phn,
    referredtopodiatrist                AS referred_to_podiatrist,
    referredtodietician                 AS referred_to_dietician,
    referredtopulmonaryrehab            AS referred_to_pulmonary_rehab,
    referredtocardiacrehab              AS referred_to_cardiac_rehab,
    referredtospecialistcare            AS referred_to_specialist_care,
    referredtosocialprescribing         AS referred_to_social_prescribing,
    referredtosmokingcessation          AS referred_to_smoking_cessation,
    referredtocounseling                AS referred_to_counseling,
    referredtophysiotherapy             AS referred_to_physiotherapy,
    referredtooccupationaltherapy       AS referred_to_occupational_therapy,
    referredtosocialwork                AS referred_to_social_work,
    otherserviceinformation             AS other_service_information,
    status                              AS status,
    printed                             AS printed,
    lastprinted                         AS last_printed,
    lastprintedby                       AS last_printed_by,
    datecreated                         AS date_created,
    datemodified                        AS date_modified,
    lastupdatedby                       AS last_updated_by,
    referredtodiabetesprevention        AS referred_to_diabetes_prevention,
    referredtostructurededucation       AS referred_to_structured_education,
    referredtoretinascreen              AS referred_to_retina_screen,
    referredtoother                     AS referred_to_other,
    remembermessage                     AS remember_message,
    anticipatoryplan                    AS anticipatory_plan,
    versionid                           AS version_id,
    gp_practice_id                      AS gp_practice_id
FROM source
