-- models/system_s/staging/stg_patientimmunisations.sql

WITH source AS (
    SELECT
        immunisationid AS immunisation_id,
        pssid AS pss_id,
        consultationid AS consultation_id,
        icpccode AS icpc_code,
        dateadministered AS date_administered,
        administeredby AS administered_by,
        methodid AS method_id,
        doseid AS dose_id,
        batchno AS batch_no,
        drugid AS drug_id,
        site AS site,
        claimperiod AS claim_period,
        additionalnotes AS additional_notes,
        datecreated AS date_created,
        datemodified AS date_modified,
        lastupdatedby AS last_updated_by,
        expirydate AS expiry_date,
        patientid AS patient_id,
        manufacturer AS manufacturer,
        agent AS agent,
        tradename AS trade_name,
        claimreceived AS claim_received,
        paidamount AS paid_amount,
        ispaid AS is_paid,
        paiddate AS paid_date,
        immunisationbatchid AS immunisation_batch_id,
        shotnumber AS shot_number,
        claimtype AS claim_type,
        gp_practice_id AS gp_practice_id
    FROM {{ source('system_s', 'patientimmunisations') }}
)

SELECT
    immunisation_id,
    pss_id,
    consultation_id,
    icpc_code,
    date_administered,
    administered_by,
    method_id,
    dose_id,
    batch_no,
    drug_id,
    site,
    claim_period,
    additional_notes,
    date_created,
    date_modified,
    last_updated_by,
    expiry_date,
    patient_id,
    manufacturer,
    agent,
    trade_name,
    claim_received,
    paid_amount,
    is_paid,
    paid_date,
    immunisation_batch_id,
    shot_number,
    claim_type,
    gp_practice_id
FROM source
